{
 "title": "Mini Node Exporter (demo)",
 "tags": [
  "node-exporter",
  "demo"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU uso (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (node) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memoria disponible (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Targets UP",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(up{job=\"node\"})"
    }
   ]
  }
 ]
}